### PR TITLE
Move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by alex-konovalov**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
I don't understand why the 32-bit test fails to push data to Codecov. This is the standard setup from the Example package. Any ideas @fingolfin @ssiccha @ChrisJefferson ?

**Comment by ssiccha** [comment]
@alex-konovalov IIRC the 32-bit tests were never able to push data to Codecov, also when we used travis.

**Comment by alex-konovalov** [comment]
@ssiccha but this is the same setup that I cloned to several packages without a problem!

**Comment by fingolfin** [comment]
I don't recall there ever being issues for 32builds with Codecov. For GAP we do them without a hitch, and have been for years, and still do them with GitHub Actions

**Comment by alex-konovalov** [comment]
@fingolfin @ssiccha and it failed again... maybe merge anyway and see if it will fail in gap-packages account?

**Comment by alex-konovalov** [comment]
Merged, and it still fails :(

**Pull request merged**
