### PR TITLE
FIX: Name of G:=PrimitiveGroup(625,672);

### PR DESCRIPTION
**Pull request by hulpke**
The old name of this group 5^4:2.Alt(5)^2.2^(2+1) indicates a wrong order
(too small).  The Name 5^4:4.(S5 wr 2) is more appropriate.

This was reported by Andries Brouwer.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@hulpke there is also CHANGES.md file - please add a description of the fix there.

**Comment by alex-konovalov** [comment]
@hulpke shall I squash and merge and publish version 3.4.1?

**Comment by hulpke** [comment]
Yes, unless there are other changes that should go in with it. I  do not have any other change pending.  Thank you,

  Alexander

On Apr 23, 2020, at 3:11 AM, Alexander Konovalov <notifications@github.com<mailto:notifications@github.com>> wrote:



@hulpke<https://github.com/hulpke> shall I squash and merge and publish version 3.4.1?

**Comment by alex-konovalov** [comment]
@hulpke v3.4.1 released!

**Pull request merged**
